#Copyright by ibhh (http://ibhh.de)
name: AnimalShop
description:  Player can buy animals
version: 3.0
author: ibhh
website: http://ibhh.de
softdepend: [Multiverse-Cores, Vault]
main: com.ibhh.animalshop.Main
database: false
commands:
  animalshop:
    description: AnimalShop main Command.
    usage: /animalshop
permissions:
  AnimalShop.*:
    description: Gives access to all xpShop commands
    children:
      AnimalShop.create: false
      AnimalShop.use: false
    description: Creates a new Shop.
    default: false
  AnimalShop.create:
    description: Allows you to create an AnimalShop.
    default: false
  AnimalShop.use:
    description: Allows you to use an AnimalShop.
    default: false